### ISSUE TITLE
Gif

### ISSUE THREAD

**Issue by hfossli** [minorblend/SnowFallView#1]
A gif would be awesome to have on the readme

**Comment by magnett** [comment]
+1

**Comment by ghost** [comment]
@hfossli @magnett thank you for your comments =)

**Comment by magnett** [comment]
@minorblend I did download it and used it and you did great! That's why I say that it needs a screenshot.
One more question though: Why did you set the min iOS version to 8.4 ? Is there some kind of limitation for iOS 8.0 or even lower?

**Comment by ghost** [comment]
@magnett AFAIK it will run well under iOS 8.4, however I have no way to test it. I might lower the minimum version to iOS 8.0 sooner or later.

**Comment by hfossli** [comment]
:+1: Looks great
